// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTvr9NjpWRqKtgU6EXoV3J6xO62nPlVBQ',
    appId: '1:106131849309:web:306a8d7e2c74336dfa8db4',
    messagingSenderId: '106131849309',
    projectId: 'adalem-50ec8',
    authDomain: 'adalem-50ec8.firebaseapp.com',
    storageBucket: 'adalem-50ec8.firebasestorage.app',
    measurementId: 'G-2H4XDN7DVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNqmrEkRgIZ7B2ftPYhMTcDddsEwc6_C0',
    appId: '1:106131849309:android:cd9a2f6108c25a61fa8db4',
    messagingSenderId: '106131849309',
    projectId: 'adalem-50ec8',
    storageBucket: 'adalem-50ec8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCtKImbFdsrsMvXnZ3veq_808La_06UKU',
    appId: '1:106131849309:ios:2ef9c5917ae79902fa8db4',
    messagingSenderId: '106131849309',
    projectId: 'adalem-50ec8',
    storageBucket: 'adalem-50ec8.firebasestorage.app',
    iosClientId: '106131849309-sbeeauqr8hd7ioc2jil0q4p6naqjbr8i.apps.googleusercontent.com',
    iosBundleId: 'com.example.adalem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCtKImbFdsrsMvXnZ3veq_808La_06UKU',
    appId: '1:106131849309:ios:2ef9c5917ae79902fa8db4',
    messagingSenderId: '106131849309',
    projectId: 'adalem-50ec8',
    storageBucket: 'adalem-50ec8.firebasestorage.app',
    iosClientId: '106131849309-sbeeauqr8hd7ioc2jil0q4p6naqjbr8i.apps.googleusercontent.com',
    iosBundleId: 'com.example.adalem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTvr9NjpWRqKtgU6EXoV3J6xO62nPlVBQ',
    appId: '1:106131849309:web:81a0a417bd2f7119fa8db4',
    messagingSenderId: '106131849309',
    projectId: 'adalem-50ec8',
    authDomain: 'adalem-50ec8.firebaseapp.com',
    storageBucket: 'adalem-50ec8.firebasestorage.app',
    measurementId: 'G-EJNFXXBBP0',
  );
}
